[versions]
minecraft = "1.20.1"
quilt_loader = "0.21.2"
quilt_mappings = "1.20.1+build.23"

quilted_fabric_api = "7.4.0+0.90.0-1.20.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
        
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.4.1" }
